version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/home/charisma
      - ./container-build/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-cli:
    image: shaunfreeman/php:7.4-cli
    working_dir: /home/charisma
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_HOST=mysql
      - PHP_IDE_CONFIG=serverName=my.local
    tty: true
    volumes:
      - .:/home/charisma
    ports:
      - "9009:9009"
    links:
      - mariadb
    depends_on:
      - mariadb

  php-fpm:
    build:
      context: .
      dockerfile: container-build/php/fpm/Dockerfile
      args:
        uid: "${UID}"
        user: "${USER}"
    working_dir: /home/charisma
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_HOST=mysql
    volumes:
      - .:/home/charisma
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=!OneTwo3
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_DATABASE=charismabeads
    volumes:
      - ./container-build/mysql/:/docker-entrypoint-initdb.d/
